 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: customercareregistry
 spec:
   replicas: 3
   selector:
     matchLabels:
       app: customercareregistry
   template:
     metadata:
       labels:
         app: customercareregistry
     spec:
       containers:
       - name: customercareregistry
         image: icr.io/bergin/customercareregistry:v1
         imagePullPolicy: Always
         ports:
         - containerPort: 5000